//
// Created by f0xeri on 09.01.2023.
//

#ifndef VULKAN_TERRAIN_SHADERSTAGE_HPP
#define VULKAN_TERRAIN_SHADERSTAGE_HPP

enum class ShaderStage
{
    VERTEX,
    TESSELLATION_CONTROL,
    TESSELLATION_EVALUATION,
    GEOMETRY,
    FRAGMENT,
    COMPUTE,
};

#endif //VULKAN_TERRAIN_SHADERSTAGE_HPP
